added url params lat,lon option, skipping main page
Amsterdam/PanoViewer pull request #6
Opened 2017-07-25 08:23 UTC by Lytrix

@boris-arkenaar Ik heb de lat lon in url toegevoegd aan de bestaande demo op advies van Stephan, zodat ik de demo omgeving kan gebruiken om te integreren. Als je geen lat lon in de url gebruikt ga je naar de bestaande startpagina, anders pak je meteen de panoviewer.

Kan jij mijn code reviewen? Heb geen html5 searchParam gebruikt omdat die niet werkt in IE. 
Er is alleen nog een probleem dat de back button niet werkt. Ik heb daar alleen nog niet een goede oplossing voor gevonden. Als je daar nog tips voor hebt graag!

2017-07-26 08:38 UTC, boris-arkenaar commented
@Lytrix Het is maar een demo. Die is niet bedoeld om te gebruiken in je eigen project. Dus ik zie niet de noodzaak voor deze wijziging.

2017-07-27 20:32 UTC, spreeker commented
@boris-arkenaar hoe meer eindgebruikers hoe beter? Als de de code nuttig is..

2017-11-07 10:35 UTC, bvhme commented
Is het mogelijk dat we deze alsnog gaan pullen? Ik denk dat onderhand is gebleken dat dit een SDK op zich is.

2017-11-07 13:26 UTC, boris-arkenaar commented
Ja. Is hier ook daadwerkelijk nog behoefte aan @Lytrix ? Dan zal ik de code review doen.

2017-11-28 09:46 UTC, Lytrix commented
@boris-arkenaar Ja er is nog steeds behoefte aan. Dan kunnen we de panos in meerdere projecten en prototypes sneller integreren. Als je nog kan code reviewen, graag!

2017-11-28 10:17 UTC, boris-arkenaar requested changes

2017-11-28 10:17 UTC, boris-arkenaar commented on demo/index.html
> +        return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
Waarom niet iets als:
```
let params = {};
location.search.substring(1).split('&').forEach((entry) => {
  const [key, value] = entry.split('=');
  params[decodeURIComponent(key)] = decodeURIComponent(value);
});
return params;
```
Misschien wat ES6 dingen in ES5 schrijven, maar zo heb je makkelijk alle search parameters in een object zitten.

2017-11-28 10:17 UTC, boris-arkenaar commented on demo/index.html
> +        if (getUrlParameter('lat') != '' && getUrlParameter('lon') != '') {
```
const params = getUrlParameters();
if (params.lat && params.lon) {
  load(params.lat, params.lon);
}
```

2017-11-28 10:17 UTC, boris-arkenaar commented on demo/index.html
> +
Dit is niet nodig

2019-02-21 07:54 UTC, closed without merging

2019-02-21 07:55 UTC, aditudorache commented
old PR